name: buy_it
description: A starter for the Shoppe eCommerce UI
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shimmer: ^3.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3 # For session management
  # The following can be kept or removed based on your preference
  # cupertino_icons: ^1.0.2
  # http: ^1.2.1
  geolocator: ^10.1.0 # For location features
  geocoding: ^2.1.0 # For reverse geocoding
  image_picker: ^1.0.7 # For profile image selection
  ionicons: ^0.2.2 # For icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/temp/
    - assets/data/
    - assets/images/
